/**
 * StockBot API endpoint paths (no base URL; client adds /api prefix and proxy strips it).
 */
export const ENDPOINTS = {
  health: '/health',
  healthDetail: '/health/detail',
  config: '/v1/config',
  runtimeStatus: '/v1/runtime/status',
  strategies: '/v1/strategies',
  signals: '/v1/signals',
  signalDetail: (uuid: string) => `/v1/signals/${uuid}`,
  intelligenceLatest: '/v1/intelligence/latest',
  intelligenceRecent: '/v1/intelligence/recent',
  intelligenceSummary: '/v1/intelligence/summary',
  shadowTrades: '/v1/shadow/trades',
  account: '/v1/account',
  accountStatus: '/v1/account/status',
  positions: '/v1/positions',
  position: (id: string) => `/v1/positions/${id}`,
  orders: '/v1/orders',
  orderDetail: (id: string) => `/v1/orders/${id}`,
  paperExposure: '/v1/paper/exposure',
  paperArmingPrerequisites: '/v1/paper/arming-prerequisites',
  paperArm: '/v1/paper/arm',
  paperDisarm: '/v1/paper/disarm',
  clock: '/v1/clock',
  calendar: '/v1/calendar',
  movers: '/v1/movers',
  assets: '/v1/assets',
  portfolioHistory: '/v1/portfolio/history',
  accountActivities: '/v1/account/activities',
  accountHistory: '/v1/account/history',
  tradesPaper: '/v1/trades/paper',
  compareBooks: '/v1/portfolio/compare-books',
  paperTestStatus: '/v1/paper/test/status',
  paperTestProof: '/v1/paper/test/proof',
  paperTestBuyOpen: '/v1/paper/test/buy-open',
  paperTestSellClose: '/v1/paper/test/sell-close',
  paperTestShortOpen: '/v1/paper/test/short-open',
  paperTestBuyCover: '/v1/paper/test/buy-cover',
  paperTestFlattenAll: '/v1/paper/test/flatten-all',
  paperTestCancelAll: '/v1/paper/test/cancel-all',
  metricsSummary: '/v1/metrics/summary',
  metricsCompareScrappyModes: '/v1/metrics/compare-scrappy-modes',
  aiRefereeRecent: '/v1/ai-referee/recent',
  aiRefereeAssessment: (id: string) => `/v1/ai-referee/${id}`,
  metricsCompareAiReferee: '/v1/metrics/compare-ai-referee',
  systemHealth: '/v1/system/health',
  systemReconciliation: '/v1/system/reconciliation',
  systemReconcileNow: '/v1/system/reconcile-now',
  scannerRunNow: '/v1/scanner/run/now',
  scannerRuns: '/v1/scanner/runs',
  scannerRun: (id: string) => `/v1/scanner/runs/${id}`,
  scannerCandidates: '/v1/scanner/candidates',
  scannerTop: '/v1/scanner/top',
  scannerSymbol: (symbol: string) => `/v1/scanner/symbol/${symbol}`,
  scannerSummary: '/v1/scanner/summary',
  scannerRunHistorical: '/v1/scanner/run/historical',
  opportunitiesRunNow: '/v1/opportunities/run/now',
  opportunitiesNow: '/v1/opportunities/now',
  opportunitiesSummary: '/v1/opportunities/summary',
  opportunitiesSession: '/v1/opportunities/session',
  opportunitiesSymbol: (symbol: string) => `/v1/opportunities/symbol/${symbol}`,
  opportunitiesHistory: '/v1/opportunities/history',
  scrappyStatus: '/v1/scrappy/status',
  scrappyAutoRuns: '/v1/scrappy/auto-runs',
  scrappyAutoRunNow: '/v1/scrappy/auto-run/now',
  scrappyRun: '/v1/scrappy/run',
  scrappyRunWatchlist: '/v1/scrappy/run/watchlist',
  backtestStatus: '/v1/backtest/status',
  backtestsRun: '/v1/backtests/run',
  backtests: '/v1/backtests',
  backtestDetail: (id: string) => `/v1/backtests/${id}`,
  backtestTrades: (id: string) => `/v1/backtests/${id}/trades`,
  backtestSummary: (id: string) => `/v1/backtests/${id}/summary`,
} as const;
